export const AUTHENTICATE = "AUTENTICATE";
export const CREATE_USER = "CREATE_USER";
export const EDIT_USER = "EDIT_USER";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_FIELDS = "FETCH_USER_FIELDS";
export const SUCCESS_CREATE_USER = "SUCCESS_CREATE_USER";
export const ERROR_CREATE_USER = "ERROR_CREATE_USER";
export const LOGIN_USER = "LOGIN_USER";

export const FETCH_GUIA = "FETCH_GUIA";
export const FETCH_GUIAS = "FETCH_GUIAS";
export const FETCH_GUIAS_RECENTES = "FETCH_GUIAS_RECENTES";
export const FETCH_FEATURED_GUIAS = "FETCH_FEATURED_GUIAS";
export const FETCH_GUIAS_FEATURED = "FETCH_GUIAS_FEATURED";

export const FETCH_CITY = "FETCH_CITY";

export const FETCH_EVENTO = "FETCH_EVENTO";
export const FETCH_EVENTOS = "FETCH_EVENTOS";
export const FETCH_EVENTOS_RECENTES = "FETCH_EVENTOS_RECENTES";

export const FETCH_NOTICIA  = "FETCH_NOTICIA";
export const FETCH_NOTICIAS = "FETCH_NOTICIAS";
export const FETCH_NOTICIAS_RECENTES = "FETCH_NOTICIAS_RECENTES";
export const FETCH_NOTICIAS_FEATURED = "FETCH_NOTICIAS_FEATURED";

export const FETCH_PAGINA  = "FETCH_PAGINA";
export const FETCH_PAGINAS = "FETCH_PAGINAS";

export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";

export const FETCH_CATEGORIES_GUIA_TOP = "FETCH_CATEGORIES_GUIA_TOP";
export const FETCH_CATEGORIES_EVENTO_TOP = "FETCH_CATEGORIES_EVENTO_TOP";

export const FETCH_BAIRRO = "FETCH_BAIRRO";
export const FETCH_BAIRROS = "FETCH_BAIRROS";

export const SEARCH_HOME = "SEARCH_HOME";